### ISSUE TITLE
upath error 

### ISSUE THREAD

**Issue by alex-e-leon** [jesstelford/changelog-verify#1]
I'm getting an error on upath's isAbsolute call.
/Users/alex.leon/Code/fe-co-get-started-alex-leon/node_modules/upath/build/code/upath.js:30
  p = p.replace(/\/g, "/");

looks like upath is only rated to work up to node v5 or maybe this is an issue only on my environment?
I'm on node 6.3.0

**Comment by alex-e-leon** [comment]
looks like it's because you're missing a dependency for upath. So instead of using the latest version (0.2.0) it was using 0.1.7 which must have come from another dependency

I've created a PR at https://github.com/jesstelford/changelog-verify/pull/2

**Comment by jesstelford** [comment]
Fixed in #2, thanks!
